export const iconArray = [
  "",
  "arrow-down",
  "arrow-right",
  "arrow-up",
  "bell",
  "bell-notification",
  "computer",
  "house-solid",
  "list",
  "medal-bronze",
  "medal-default",
  "medal-gold",
  "medal-silver",
  "play",
  "plus",
  "send-black",
  "user",
  "woman_avatar",
  "man_thinking",
  "woman_large_pink_hair",
  "woman_blue_dress",
  "woman_v_sign",
  "woman_heart_sign",
  "man_thumb_up",
  "man_with_dog",
];

export const iconList = {
  None: "",
  arrowDown: "arrow-down",
  arrowRight: "arrow-right",
  arrowUp: "arrow-up",
  bell: "bell",
  bellNotification: "bell-notification",
  bronzeMedal: "medal-bronze",
  computer: "computer",
  defaultMedal: "medal-default",
  goldMedal: "medal-gold",
  houseSolid: "house-solid",
  list: "list",
  play: "play",
  plus: "plus",
  send: "send-black",
  silverMedal: "medal-silver",
  user: "user",
  avatarWoman: "woman_avatar",
  avatarManThinking: "man_thinking",
  avatarWomanPinkHair: "woman_large_pink_hair",
  avatarWomanBlueDress: "woman_blue_dress",
  avatarWomanVSign: "woman_v_sign",
  avatarWomanHeartSign: "woman_heart_sign",
  avatarManThumbUp: "man_thumb_up",
  avatarManWithDog: "man_with_dog",
};
